---
# file: oracle-java/tasks/installation/redhat/main.yml
#
# Task file to install Oracle Java Development Kit in a system with a Redhat based Linux distribution.
#

- name: Install Java RPM
  yum:
    name="{{ oracle_java_dir_source }}/{{ oracle_java_rpm_filename }}"
    state=present
  become: yes

- name: set Java version as default
  alternatives:
    name="{{ java.exe }}"
    link="/usr/bin/{{ java.exe }}"
    path="{{ java.path }}/{{ java.exe }}"
  with_items:
    - { path: "{{ oracle_java_home }}/bin", exe: 'java' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'keytool' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javac' }
    - { path: "{{ oracle_java_home }}/bin", exe: 'javadoc' }
  loop_control:
      loop_var: java
  become: yes
  when: oracle_java_set_as_default
  register: oracle_java_task_set_default
