- hosts: all
  gather_facts: no
  roles:
    -
      role: setup-server
      become: yes
      ansible_ssh_user: root
      ansible_ssh_pass: '{{ root_original_password }}'
      username: '{{ dmms_user }}'
      password: '{{ dmms_user_password }}'
