---
- name: start services
  service: name={{ item }} state=started
  register: result
  failed_when: ( result.msg is defined and "Could not find the requested service" not in result.msg )
  ignore_errors: yes
  with_items: '{{ deployment_services }}'
