- name: '{{ service_name }}: app directory'
  file:
    path: '{{ app_dir }}'
    state: directory
    owner: admin
    group: admin

- name: '{{ service_name }}: config directory'
  file:
    path: '{{ app_dir }}/config'
    state: directory
    owner: admin
    group: admin

- name: '{{ service_name }}: system service'
  template:
    src: 'service.j2'
    dest: '/etc/systemd/system/{{ service_name }}.service'
    mode: 0655
  register: system_config

- name: '{{ service_name }}: deamon reload'
  shell: systemctl daemon-reload
  when: system_config is changed

- name: '{{ service_name }}: service stop'
  service:
    name: '{{ service_name }}'
    state: stopped

- block:
  - name: '{{ service_name }}: service config files'
    template:
      src: '{{ item.template }}'
      dest: '{{ app_dir }}/config/{{ item.config_name }}'
      force: yes
      owner: admin
      group: admin
    with_items: "{{ config_files }}"
  when: config_files is defined

- name: '{{ service_name }} : copying jar to server'
  copy:
    src: '{{ jar_location }}'
    dest: '{{ app_jar_path }}'
    force: yes
    owner: admin
    group: admin

- name: '{{ service_name }} : enable service'
  service:
    name: '{{ service_name }}'
    enabled: yes
