- name: '{{ service_name }}: configure NGINX proxy'
  template:
    src: 'proxy.conf.j2'
    dest: '/etc/nginx/conf.d/{{ service_name }}.conf'
    owner: nginx
    group: nginx
    mode: 0400

- name: '{{ service_name }}: ensure firewall started'
  service:
    name: firewalld
    state: started
    enabled: yes

- name: '{{ service_name }}: open firewall port'
  firewalld:
    port: '{{ https_port }}/tcp'
    permanent: true
    state: enabled

- name: '{{ service_name }}: reload firewall'
  service: name=firewalld state=reloaded

- name: '{{ service_name }}: reload NGINX'
  service:
    name: nginx
    state: reloaded
