- name: Install Certbot for NGINX
  yum:
    name: python2-certbot-nginx
    state: latest

- name: Check if certificate exists
  shell: certbot certificates | grep "No certs found."
  ignore_errors: true
  register: certificates_installed

- block:
  - name: Replace server_name in NGINX config
    lineinfile:
      path: '/etc/nginx/conf.d/default.conf'
      regexp: 'server_name'
      line: 'server_name {{ domain_name }};'

  - name: Reload NGINX
    service:
      name: nginx
      state: reloaded

  - name: Create letsencrypt certificate
    shell: certbot --nginx certonly -n -m {{ letsencrypt_email }} -d {{ domain_name }} --agree-tos

  - name: Add letsencrypt cronjob for cert renewal
    cron:
      name: letsencrypt_renewal
      special_time: weekly
      job: letsencrypt --renew certonly --nginx -n -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }} && systemctl reload nginx

  - name: Restart NGINX
    service:
      name: nginx
      state: restarted
  when: certificates_installed.rc == 0
