- name: Install SELinux minimum policy
  yum:
    name: selinux-policy-minimum
    state: present
  tags: online

- name: Set SELinux config permissive
  selinux:
    policy: minimum
    state: permissive

- name: Install NGINX
  include_role:
    name: nginx-installation

- name: Open ports in firewalld
  firewalld:
    port: '{{ item }}/tcp'
    permanent: true
    state: enabled
  with_items:
    - '80'
    - '443'

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted

- import_tasks: 'cert.yml'
  when: '{{ install_cert }}'

- name: Remove default NGINX service
  file:
    path: '/etc/nginx/conf.d/default.conf'
    state: absent

- name: Create default NGINX conf
  template:
    src: 'nginx-default.conf.j2'
    dest: '/etc/nginx/conf.d/nginx-default.conf'
    owner: admin
    group: admin

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
