- name: Get the username running the deploy
  become: no
  local_action: command whoami
  register: username_on_the_host

- name: Set facts
  set_fact:
    nginx_cert_file: '/tmp/nginx.crt'
    nginx_key_file: '/tmp/nginx.key'
    username: '{{ username_on_the_host.stdout }}'

- name: Create cert file
  become: no
  become_user: '{{ username }}'
  copy:
    content: '{{ nginx_cert }}'
    dest: '{{ nginx_cert_file }}'
    owner: '{{ username }}'
    group: '{{ username }}'
  delegate_to: localhost

- name: Create private key file
  become: no
  become_user: '{{ username }}'
  copy:
    content: '{{ nginx_private_key }}'
    dest: '{{ nginx_key_file }}'
  delegate_to: localhost

- name: Install NGINX
  include_role:
    name: nginx-installation
  vars:
    nginx_ssl_upload_enable: true
    nginx_ssl_crt_upload_src: '{{ nginx_cert_file }}'
    nginx_ssl_crt_upload_dest: '/etc/nginx/ssl/'
    nginx_ssl_key_upload_src: '{{ nginx_key_file }}'
    nginx_ssl_key_upload_dest: '/etc/nginx/ssl/'

- name: Remove default NGINX service
  file:
    path: '/etc/nginx/conf.d/default.conf'
    state: absent

- name: Create https redirect service
  copy:
    src: 'https-redirect.conf'
    dest: '/etc/nginx/conf.d/https-redirect.conf'

- name: Restart NGINX
  service:
    name: nginx
    state: restarted

- name: Remove temp files
  become_user: '{{ username }}'
  file:
    state: absent
    path: '{{ item }}'
  with_items:
    - '{{ nginx_cert_file }}'
    - '{{ nginx_key_file }}'
  delegate_to: localhost
