- name: Download Java RPM
  shell: 'wget https://www.dropbox.com/s/z9khdco1kgzuh5o/jdk-8u212-linux-x64.rpm -P /usr/local/src/'

- name: Install Oracle Java 8
  include_role:
    name: java-installation
  vars:
    oracle_java_use_defaults: no
    oracle_java_dir_source: '/usr/local/src'
    oracle_java_download_timeout: 60
    oracle_java_rpm_filename: 'jdk-8u212-linux-x64.rpm'
    oracle_java_home: '/usr/java/default'
    oracle_java_os_supported: yes
    oracle_java_rpm_url: 'https://www.dropbox.com/s/z9khdco1kgzuh5o/jdk-8u212-linux-x64.rpm'
    oracle_java_set_as_default: yes
